services:
  app:
    build: .
    container_name: eduraag-app
    restart: always
    network_mode: host
    volumes:
      - ./rag_qa/model:/app/rag_qa/model
      - ./rag_qa/core/bert_query_classifier:/app/rag_qa/core/bert_query_classifier
      - ./rag_qa/data:/app/rag_qa/data
      - ./config.ini:/app/config.ini
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
